name: 🛠️ Build main firmware

on:
 workflow_dispatch:
 push:
    paths: [ "main/*" ]


jobs:

  # Compile code

  compile:

    runs-on: ubuntu-latest
    
    steps:

      # Clone repository
      
      - name: Clone repository
        uses: actions/checkout@v3

      # Setup arduino CLI
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # Configure platform
      
      - name: Configure platform
        run: |
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          
      # Compile
      
      - name: Compile sketch
        run: |
          arduino-cli compile -b "esp8266:esp8266:nodemcuv2" -e ./sketch
      
      # Move file to better place

      - name: Find compiled file
        run: |
          cp ./sketch/build/*.*.*/*.ino.bin ./firmware-main.bin

      # Upload to artifacts

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware-main.bin
          path: firmware-main.bin
